Algoritmo "semnome"
// 
//  
//
Var
// Seção de Declarações das variáveis 
nome : inteiro
frase : caracter
vezes : inteiro




Inicio
// Seção de Comandos



    escreval()
     escreval ( " digite uma frase a ser repetida ")
      leia (frase)
       escreval (" quantas vezes ")
        leia (vezes)


         para vezes<- 1 ate vezes faca
         escreval ( frase, " -" , vezes )
         fimpara


Fimalgoritmo