Algoritmo "semnome"
// 


Var
// Seção de Declarações das variáveis 
  graucelsius : real
  grauF : real
  temperatura : real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  escreval ( " insira o valor da temperatura em Graus Celsius" )
  leia (graucelsius)
  
  //
   grauF <- (9*graucelsius+160)/5
    //
     escreval ( " o valor da temperatura em FAHRENHEIT é : ", grauF)
     


  

Fimalgoritmo