Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/08/2020
Var
// Seção de Declarações das variáveis 
area :real
raio : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  escreval ( " insira o raio da area")
   leia (raio)
 raio <- raio*raio
 raio <- raio*3,14159
  escreval ( " a sua área vale : ", raio )
  

Fimalgoritmo