Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/08/2020
Var
// Seção de Declarações das variáveis 
num,i,m : inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
i <-1
enquanto num <=1000 faca
i<- i+1
m <-7
num <-m*i
 escreval("7 x " , i , " = ",num)
 fimenquanto
Fimalgoritmo