Algoritmo "semnome"
// 


Var
// Seção de Declarações das variáveis 
  graucelsius : real
  grauF : real
  temperatura : real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  escreval ( " insira o valor da temperatura em Graus fahrenheit" )
  leia (grauf)
  
  //
  graucelsius <-(grauF-32)*(5/9)
    //
     escreval ( " o valor da temperatura em CELSIUS é : ", graucelsius)
     


  

Fimalgoritmo